- name: setup carbon
  pip: name=carbon state=present version=0.9.12

- name: create /opt/graphite/conf/
  file: dest=/opt/graphite/conf/ state=directory
  
- name: put carbon config
  template: src=carbon.conf dest=/opt/graphite/conf/carbon.conf owner=root group=root mode=0644

- name: put carbon storage schemas description
  template: src=storage-schemas.conf dest=/opt/graphite/conf/storage-schemas.conf owner=root group=root mode=0644

- name: put carbon service descriptor
  template: src=carbon-eye.rb dest=/etc/eye/carbon.rb owner=root group=root mode=0644

- name: load config in eye
  command: bash -c "source /usr/local/rvm/scripts/rvm && eye l /etc/eye/apps.eye"
  sudo: yes
