# python-virtualenv

- name: install dependencies
  apt: name={{ item }}
  with_items:
    - python-pip
    - python-dev
    - libffi-dev
    - gunicorn
    - libcairo2-dev
    - gcc

- name: install required pips
  pip: name={{ item }}
  with_items:
    - graphite-api
    # - cyanite

# install latest version of graphite-cyanite as the one in pip is still broken, see
# https://github.com/brutasse/graphite-cyanite/issues/14
# https://github.com/pyr/cyanite/issues/119
# https://github.com/brutasse/graphite-api/issues/123

- name: install graphite-cyanite
  command: pip install git+https://github.com/gitinsky/graphite-cyanite#egg=cyanite-master
  tags: pip

# - name: install graphite-cyanite
#   pip: name=git+https://github.com/brutasse/graphite-cyanite.git#egg=cyanite
#   tags: pip

- name: configure graphite-api
  template: src=graphite-api.yaml dest=/etc/graphite-api.yaml
  notify:
      - eye restart graphite-api
  tags: gapiconf

- name: create graphite index
  file: dest={{ item.dst }} state={{ item.state }}
  with_items:
      - { dst: /srv/graphite, state: directory }
      - { dst: /srv/graphite/index, state: touch }

 
- name: put gunicorn service descriptor
  template: src=graphite-api.rb dest=/etc/eye/graphite-api.rb owner=root group=root mode=0644
  notify:
      - reload eye configs
      - eye restart graphite-api

- name: load config in eye
  command: bash -c "source /usr/local/rvm/scripts/rvm && eye l /etc/eye/apps.eye"

- name: configure graphite-api nginx
  template: src=sites-available/graphite.conf dest=/etc/nginx/sites-available/graphite.conf
  notify: nginx reload

- name: make a site-enabled link
  file: state=link src=/etc/nginx/sites-available/graphite.conf dest=/etc/nginx/sites-enabled/graphite.conf
  notify: reload nginx


# If you run Cyanite on multiple hosts, specify all of them to load-balance traffic
