- name: install dependencies
  apt: name={{ item }}
  with_items:
    - python-pip
    - python-dev
    - libffi-dev
    - gunicorn
    - libcairo2-dev
    - gcc

- name: install required pips
  pip: name={{ item }}
  with_items:
    - graphite-api
  notify:
      - eye restart graphite-api

# - name: configure graphite-api
#   template: src=graphite-api.yaml dest=/etc/graphite-api.yaml
#   notify:
#       - eye restart graphite-api
#   tags: gapiconf

- name: create graphite index
  file: dest={{ item.dst }} state={{ item.state }}
  with_items:
      - { dst: /srv/graphite, state: directory }
      - { dst: /srv/graphite/index, state: touch }
  notify:
      - eye restart graphite-api
 
- name: put gunicorn service descriptor
  template: src=graphite-api.rb dest=/etc/eye/graphite-api.rb owner=root group=root mode=0644
  notify:
      - reload eye configs
      - eye restart graphite-api

- name: load config in eye
  command: bash -c "source /usr/local/rvm/scripts/rvm && eye l /etc/eye/apps.eye"
